version: "3.8"

services:
  ticker:
    build:
      context: .
    devices:
      - "/dev/mem:/dev/mem"
    privileged: true
    restart: always
    env_file:
      - ./settings.env
    volumes:
      - .:/code
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
    tmpfs:
      - /tmp:size=10M
